version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=legalmate
      - POSTGRES_USER=legalmate_user
      - POSTGRES_PASSWORD=secure_password
    ports:
      - "5432:5432"